# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5cca350093791c65df399111eba969451de42833189370e2712900092475e804035c0be62cfca6c26d8d4f72f39ca53697195918d4ac8b8dadeb4a42a2a37d08

test:
  secret_key_base: 0f4a56f2629c3d0c8411c2fc5db273784a385152a054ddc9b8f0e399bc2bdeb4e8ec2691d2d948fc4aea5fe64086c3f4a802c63388d0ef854365c03598249480

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
